### ISSUE TITLE
Replace SirenClient with Top-Level Functions

### ISSUE THREAD

**Issue by dillonredding** [siren-js/client#12]
Rather than having to instantiate a `SirenClient`, users should be able to use top-level `follow` and `submit` actions. This better satisfies the [Interface Segregation Principle](https://en.wikipedia.org/wiki/Interface_segregation_principle) and aligns better with the style of the [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API).

**Comment by SeeSharpCode** [comment]
@dillonredding do you have ideas for how to handle HTTP headers with top-level functions? Pass them to each follow/submit call?

**Comment by dillonredding** [comment]
@SeeSharpCode They could accept an options parameter that aligns with the `fetch` function's (see [here-ish](https://developer.mozilla.org/en-US/docs/Web/API/fetch#syntax)). For `submit`, it might be nested in a larger options object that also accepts serializers, encoding config, etc.
